name: first_workflow
on: workflow_dispatch
jobs:
  first_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: First_step
        run: |
          echo "First run command output"
          echo "Second run command output"
      - name: Last_step
        run: echo "Goodbye !!"
        
  
